### PR TITLE
Enable adding relationships to Components

### PR DESCRIPTION
**Pull request by maciejwalkowiak**

### CODE REVIEW

**Comment by ChristianEder** [comment]
Oh - wow. I totally forgot about that. Thanks :-)

**Comment by ChristianEder** [comment]
just published version 0.0.21 containing your fix - can you verify it works now?

**Comment by maciejwalkowiak** [comment]
Thanks @ChristianEder for quick merge. Works fine now! 

Thanks for putting work into this library. I find it much better option in polyglot environment than Java or .NET equivalent.

**Comment by ChristianEder** [comment]
Great - and let me know if you are missing any features that are availabe for .NET or Java that you are missing , it helps me with prioritization. I always love to see when folks are actually using my stuff :-)

**Pull request merged**
