### PR TITLE
Rewrite of the sample

### PR DESCRIPTION
**Pull request by zvictor**
This is pretty much an alternative version of #15. I was trying to fix the script and ended up reformatting it completely.
I believe this is easier for newcomers to understand what is happening there.

### CODE REVIEW

**Comment by ChristianEder** [comment]
Hi @zvictor - just a brief heads up, I didn't forget you, but pretty much under load right now, will get back to this.

Thanks for your contribution in advance!

**Comment by ChristianEder** [comment]
Just merged it, thanks for the rewrite, I agree that its clearer like that - will probably refactor the individual functions into their own files.

**Comment by zvictor** [comment]
Cool! I just noticed you are combining structurizr and pulumi. That's nice! I hope to see more on that direction =)

**Comment by ChristianEder** [comment]
Yep I'm working on stuff like that for a while now. If you happen to be on the .NET Day Franken this Friday, you can come to my workshop on that topic :-)

**Comment by zvictor** [comment]
Unfortunately I won't have the chance to be there, but I will keep an eye on your progress around here. Thanks!

**Pull request merged**
