### PR TITLE
Add support for properties

### LINKED ISSUE #34: Support for properties
It would be very useful to have support for properties: https://docs.structurizr.com/dsl/language#properties

What do you think about this? Is there something to consider when trying to contribute this?

### PR DESCRIPTION
**Pull request by erikhofer**
closes #34

### CODE REVIEW

**Comment by ChristianEder** [comment]
Thanks @erikhofer for this, always happy to get contributions! 

Code wise the change looks good to me (generally I try to stay close to the „official“ Java and C# versions of the SDK as a general coding guideline, which seems to be the case for your change.

one small thing: could you bump the version in package.json to 1.0.13? This it’ll be automatically published after merge 👍

**Comment by erikhofer** [comment]
@ChristianEder Done. I ran `npm version patch` which also updated `package-lock.json`. Is this correct?

**Comment by ChristianEder** [comment]
fyi - the two failing tests are very likely not related to your PR - they are integration testing against the Structurizr backend api and might be running into throttling issues. I’ll double check and improve logging of errors for the failed tests

**Comment by ChristianEder** [comment]
@erikhofer just an FYI 

THANKS again for this PR, as it happens, I am just today happening to need the properties feature myself for the first time, so I'm happy its in by now already :-)

**Pull request merged**
